import type { ThemeDefinition } from 'vuetify';

export const mdiLightTheme: ThemeDefinition = {
  dark: false,
  colors: {
    primary: '#6750A4',
    'on-primary': '#FFFFFF',
    'primary-container': '#EADDFF',
    'on-primary-container': '#21005D',
    secondary: '#625B71',
    'on-secondary': '#FFFFFF',
    'secondary-container': '#E8DEF8',
    'on-secondary-container': '#1D192B',
    tertiary: '#7D5260',
    'on-tertiary': '#FFFFFF',
    'tertiary-container': '#FFD8E4',
    'on-tertiary-container': '#31111D',
    error: '#B3261E',
    'on-error': '#FFFFFF',
    'error-container': '#F9DEDC',
    'on-error-container': '#410E0B',
    outline: '#79747E',
    background: '#FFFBFE',
    'on-background': '#1C1B1F',
    surface: '#FFFBFE',
    'on-surface': '#1C1B1F',
    'surface-variant': '#E7E0EC',
    'on-surface-variant': '#49454F',
    'inverse-surface': '#313033',
    'inverse-on-surface': '#F4EFF4',
    'inverse-primary': '#D0BCFF',
    shadow: '#000000',
    'surface-tint': '#6750A4',
    'outline-variant': '#CAC4D0',
    scrim: '#000000',
  },
};

export const mdiDarkTheme: ThemeDefinition = {
  dark: true,
  colors: {
    primary: '#D0BCFF',
    'on-primary': '#381E72',
    'primary-container': '#4F378B',
    'on-primary-container': '#EADDFF',
    secondary: '#CCC2DC',
    'on-secondary': '#332D41',
    'secondary-container': '#4A4458',
    'on-secondary-container': '#E8DEF8',
    tertiary: '#EFB8C8',
    'on-tertiary': '#492532',
    'tertiary-container': '#633B48',
    'on-tertiary-container': '#FFD8E4',
    error: '#F2B8B5',
    'on-error': '#601410',
    'error-container': '#8C1D18',
    'on-error-container': '#F9DEDC',
    outline: '#938F99',
    background: '#1C1B1F',
    'on-background': '#E6E1E5',
    surface: '#1C1B1F',
    'on-surface': '#E6E1E5',
    'surface-variant': '#49454F',
    'on-surface-variant': '#CAC4D0',
    'inverse-surface': '#E6E1E5',
    'inverse-on-surface': '#313033',
    'inverse-primary': '#6750A4',
    shadow: '#000000',
    'surface-tint': '#D0BCFF',
    'outline-variant': '#49454F',
    scrim: '#000000',
  },
};
