version: "3.8"
services:

  keycloak:
    build:
      dockerfile: ./keycloak.Dockerfile
    container_name: keycloak
    restart: unless-stopped
    ports:
      - "8443:8443"
#      - "8080:8080"
    env_file:
      - keycloak-config.env
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: 71FXUauCRnMFPvwQ5zIT1giFdz8eE
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./src/config/keycloak/realm-local.json:/opt/keycloak/data/import/realm-local.json
    command: "start --optimized --import-realm"
    #    command: "start --optimized"
    depends_on:
      - postgres
    networks:
      - keycloak-network
#      - app-network

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
#    ports:
#      - "8080:8080"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - keycloak-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "keycloak"]
    networks:
      - keycloak-network


#  adminer:
#    image: adminer
#    container_name: adminer
#    restart: always
#    ports:
#      - 81:8080

volumes:
  keycloak-data:

networks:
  keycloak-network:
    driver: bridge
#  app-network:
#    driver: bridge
