version: "3.8"
services:

  keycloak:
    build:
      dockerfile: ./keycloak.Dockerfile
    container_name: keycloak
    ports:
      - "8443:8443"
#      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_HOSTNAME: keycloak.home.loc
    volumes:
        - ./src/config/keycloak/realm-local.json:/opt/keycloak/data/import/realm-local.json
    command: "start --optimized --import-realm"
    #    command: "start --optimized"
    depends_on:
      - postgres
    networks:
      - app-network
      - keycloak-network

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
#    ports:
#      - "8080:8080"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - keycloak-data:/var/lib/postgresql/data
    networks:
      - keycloak-network


#  adminer:
#    image: adminer
#    container_name: adminer
#    restart: always
#    ports:
#      - 81:8080

volumes:
  keycloak-data:

networks:
  keycloak-network:
    driver: bridge
  app-network:
    driver: bridge
